# -*- coding: utf-8 -*-
#"""Sistema Multiagente.ipynb

#Automatically generated by Colab.

#Original file is located at
#    https://colab.research.google.com/drive/10iRWyIJJMTJGJj8mB2QhvKnCPpseY4mZ
#"""

#!pip install crewai
#!pip install 'crewai[tools]'
#!pip install google-genai
#!pip install langchain-google-genai
#!pip install litellm

# ==============================================================================
# 1. INSTALAÇÃO E CONFIGURAÇÃO
# OBJETIVO: Preparar o ambiente no Colab, instalar dependências e configurar o LLM (Gemini)
# ==============================================================================

import os
from google import colab
from crewai import Agent, Task, Crew, Process, LLM 


try:
    if 'GEMINI_API_KEY' not in os.environ:
        os.environ['GEMINI_API_KEY'] = colab.userdata.get('GEMINI_API_KEY')
except:
    MINHA_CHAVE_REAL = "AIzaSyCkCFjK5JcUcI2i6_J2JHbFRZ8BGgJEvqM"
    os.environ["GEMINI_API_KEY"] = MINHA_CHAVE_REAL


llm_model = LLM(
    provider='google', # Define explicitamente o provedor como 'google'
    model='gemini-2.5-flash', # Define o modelo
    temperature=0.4,
)

#===============================================================================
# 2. CRIAÇÃO DOS AGENTES: O TIME DE CRIAÇÃO DE CONTEÚDO TECH
# OBJETIVO: Definir 3 especialistas (Agentes) com papéis distintos para garantir
# a pesquisa, a redação criativa e a validação técnica do post.
# ==============================================================================

analista_dev = Agent(
    role="Especialista em Tendências Tech e Dados",
    goal="Identificar e analisar as principais vantagens e a adoção de um novo framework de desenvolvimento Web (Astro).",
    backstory="Um ex-CTO que passou anos estudando a evolução de frameworks front-end e o mercado de trabalho em TI, focado em precisão e dados atualizados.",
    verbose=True,
    llm=llm_model
)

redator_viral = Agent(
    role="Estrategista de Engajamento e Copywriter",
    goal="Transformar dados técnicos em um texto atraente, otimizado para o LinkedIn e com alta taxa de engajamento.",
    backstory="Um guru do marketing de conteúdo com 5 anos de experiência em escrita que converte no LinkedIn e TikTok, especialista em ganchos fortes e uso estratégico de emojis.",
    verbose=True,
    llm=llm_model
)

revisor_codigo = Agent(
    role="Verificador de Precisão Técnica",
    goal="Assegurar que todas as informações técnicas e exemplos de código no post estão 100% corretos e atualizados, e que o português está impecável.",
    backstory="Um desenvolvedor sênior detalhista, focado em qualidade de código e documentação. Ele não deixa passar um erro técnico ou gramatical e é expert em clareza.",
    verbose=True,
    llm=llm_model
)

print("✅ Agentes Criados com Sucesso!")

# ==============================================================================
# 3. CRIAÇÃO DAS TAREFAS (Workflow Sequencial)
# OBJETIVO: Definir as etapas de trabalho e a ordem de execução. O processo é
# sequencial: Pesquisa -> Redação -> Revisão.
# ==============================================================================

# Tarefa 1: Pesquisa (Atribuída ao Analista de Mercado Dev)
tarefa_pesquisa = Task(
    description = "Pesquisar e resumir os 3 principais pontos positivos, o cenário de uso ideal (Ex: blogs, e-commerce estático) e uma desvantagem crucial do framework de desenvolvimento web 'Astro'.",
    expected_output = "Um resumo conciso de 300 a 500 palavras, com listas claras de prós, contras e o cenário de uso ideal do Astro, escrito em português.",
    agent = analista_dev
)

# Tarefa 2: Redação (Atribuída ao Redator de Conteúdo Viral)
tarefa_redacao = Task(
    description = (
        "Com base **EXCLUSIVAMENTE** no resumo da pesquisa anterior, redigir um post profissional e persuasivo para o LinkedIn, focado em atrair Desenvolvedores Júnior e Pleno. "
        "O post deve ter um gancho de 1ª linha forte, usar emojis relevantes e a estrutura de parágrafos curtos do LinkedIn (máximo 3 linhas por parágrafo)."
    ),
    expected_output = "Um rascunho completo do post (entre 1200 e 1800 caracteres), com quebras de linha estratégicas, hashtags relevantes (como #Astro #DevWeb #Frameworks) e um Call to Action (CTA) claro para interagir no final.",
    agent = redator_viral,
    context=[tarefa_pesquisa] # Usa o output da tarefa anterior
)

# Tarefa 3: Revisão (Atribuída ao Revisor de Código e Fatos)
tarefa_revisao = Task(
    description = (
        "Revisar o rascunho do post do LinkedIn. Corrigir erros de português, garantir a coesão e a fluidez do texto. "
        "A principal função é **VALIDAR** que todas as alegações técnicas sobre o Astro estão 100% corretas e alinhadas ao contexto da pesquisa."
    ),
    expected_output = "A versão FINAL, impecável, validada tecnicamente e pronta para ser publicada no LinkedIn. O texto deve ser coeso e envolvente.",
    agent = revisor_codigo,
    context=[tarefa_redacao] # Usa o output da tarefa anterior
)

print("✅ Agentes e Tarefas Definidos!")

# ==================================================================================
# 4. MONTAGEM E EXECUÇÃO DA CREW
# OBJETIVO: Reunir agentes e tarefas para iniciar o processo sequencial de trabalho.
# ==================================================================================

tech_crew = Crew(
    agents = [analista_dev, redator_viral, revisor_codigo],
    tasks = [tarefa_pesquisa, tarefa_redacao, tarefa_revisao],
    process = Process.sequential, # O fluxo de trabalho segue a ordem das tarefas
    verbose = True # Mostra o progresso
)

print("\n--- Iniciando o Processo de Criação de Conteúdo (tech_crew.kickoff()) ---")

# Inicia a execução da equipe!
resultado = tech_crew.kickoff()

print("\n\n################################################################################")
print("                 RESULTADO FINAL DO POST PARA LINKEDIN")
print("################################################################################\n")
print(resultado)
